import { Providers } from "@/redux/providers";
import type { Metadata } from "next";
// import Script from "next/script";
import { ReactNode } from "react";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Algoricum",
  description: "Generated by Algoricum",
};

export default function RootLayout({ children }: { children: ReactNode[] | ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
