import { Providers } from "@/redux/providers";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Algoricum",
  description: "Generated by Algoricum",
};

export default function RootLayout({ children }: { children: ReactNode[] | ReactNode }) {
  return (
    <html lang="en">
      <head>
      <script src="http://localhost:9000/hash-sdk.js"></script>
  </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
